version: "3.9"

services:
  keycloak_postgres:
    container_name: keycloak_example.keycloak_postgres
    image: postgres:15-alpine
    hostname: keycloak_example.keycloak_postgres
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - 127.0.0.1:15432:5432
    networks:
      - keycloak_example.keycloak_postgres.network
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: ${POSTGRES_USER:-$USER}
      POSTGRES_DB: ${POSTGRES_DB:-keycloak}
    volumes:
      - keycloak_example.keycloak_postgres.data:/var/lib/postgresql/users:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s

  keycloak:
    container_name: keycloak_example.keycloak
    image: keycloak/keycloak:22.0
    hostname: keycloak_example.keycloak
    restart: unless-stopped
    ports:
      - 3000:8080
      - 8080:8080
    networks:
      - keycloak_example.keycloak_postgres.network
    environment:
      # Host region start
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME:-localhost}
      KC_HOSTNAME_PORT: ${KEYCLOAK_HOSTNAME_PORT:-8080}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-change_me}
      # Host region end
      # Database region start
      KC_DB: ${KEYCLOAK_DB_VENDOR:-postgres}
      KC_DB_ADDR:
        # By default, we use database address by shared network, but you can start keycloak locally and pass its address
        ${KEYCLOAK_DB_ADDR:-keycloak_example.keycloak_postgres}
      KC_DB_PORT: ${KEYCLOAK_DB_PORT:-5432}
      KC_DB_URL:
        # By default, JDBC URL is creating by yourself, but you can pass variant in `KEYCLOAK_JDBC_URL`
        ${KEYCLOAD_JDBC_URL:-jdbc:${KEYCLOAK_JDBC_VENDOR:-postgresql}://$${KC_DB_ADDR}:$${KC_DB_PORT}/${KEYCLOAK_DB_NAME}?characterEncoding=UTF-8}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME:-$${POSTGRES_USER}}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-$${POSTGRES_PASSWORD}}
      # Database region end
      KC_FEATURES: ${KEYCLOAK_FEATURES}
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: ${KEYCLOAK_METRICS_ENABLED:-true}
    volumes:
      - keycloak_example.keycloak.data:/opt/keycloak/data/import:rw
    depends_on:
      keycloak_postgres:
        condition: service_healthy
    command: ['start-dev']

volumes:
  keycloak_example.keycloak_postgres.data: {}
  keycloak_example.keycloak.data: {}

networks:
  keycloak_example.keycloak_postgres.network: {}
