version: "3.9"

services:
  postgres:
    container_name: keycloak.postgres
    image: postgres:15-alpine
    hostname: keycloak.postgres
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - 127.0.0.1:15432:5432
    networks:
      - keycloak.postgres.network
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: ${POSTGRES_USER:-$USER}
      POSTGRES_DB: ${POSTGRES_DB:-keycloak}
    volumes:
      - keycloak.postgres.data:/var/lib/postgresql/users:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s

  keycloak:
    container_name: keycloak.keycloak
    image: keycloak/keycloak:22.0
    hostname: keycloak.keycloak
    restart: unless-stopped
    ports:
      - 3000:8080
      - 8080:8080
    environment:
      # Host region start
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME:-localhost}
      KC_HOSTNAME_PORT: ${KEYCLOAK_HOSTNAME_PORT:-8080}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-change_me}
      # Host region end
      # Database region start
      KC_DB: ${KEYCLOAK_DB_VENDOR:-postgres}
      KC_DB_ADDR: ${KEYCLOAK_DB_ADDR:-keycloak.postgres}
      KC_DB_PORT: ${KEYCLOAK_DB_PORT:-5432}
      KC_DB_URL: ${KEYCLOAK_DB_URL:-jdbc:postgresql://keycloak.postgres/keycloak/}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME:-$${POSTGRES_USER}}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-$${POSTGRES_PASSWORD}}
      # Database region end
      KC_FEATURES: ${KEYCLOAK_FEATURES}
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: ${KEYCLOAK_METRICS_ENABLED:-true}
    networks:
      - keycloak.postgres.network
    depends_on:
      postgres:
        condition: service_healthy
    command: ['start-dev']

volumes:
  keycloak.postgres.data: {}

networks:
  keycloak.postgres.network: {}